### ISSUE TITLE
Imprint & Data Privacy on different domain

### ISSUE THREAD

**Issue by sdoering** [sinnerschrader/sinnerschrader-reboot#126]
**Describe the bug**

Currently clicking on the imprint and/or data privacy links in the footer leads the user to a page on github.com. I am not sure, that this is legally feasible. 

**To Reproduce**

Click on Imprint and/or "Data Privacy" link in the footer to be transported to a github page. 

**Expected behavior**

Imprint and Data Privacy page is expected to be on the first party domain (sinnerschrader.com) 

**Additional context**

**Comment by timbru31** [comment]
Thanks Sven - yes we know that this solution might not be 100% ideal, but we are already working on adding this pages asasp 👍
